const w = {
  // means WORD of entity or drop
  repos: {
    name: 'repo',
    nameId: 'repoId',
    Name: 'Repo',
    names: 'repos',
    Names: 'Repos',
    NAMES: 'REPOS',
    naming: 'repository',
    Naming: 'Repository',
    namings: 'repositories',
    Namings: 'Repositories'
  },
  deps: {
    name: 'dep',
    nameId: 'depId',
    Name: 'Dep',
    names: 'deps',
    Names: 'Deps',
    NAMES: 'DEPS',
    naming: 'deployment',
    Naming: 'Deployment',
    namings: 'deployments',
    Namings: 'Deployments'
  },
  otherDeps: {
    name: 'otherDep',
    nameId: 'otherDepId',
    Name: 'OtherDep',
    names: 'otherDeps',
    Names: 'OtherDeps',
    NAMES: 'OTHER_DEPS',
    naming: 'other deployment',
    Naming: 'Other Deployment',
    namings: 'other deployments',
    Namings: 'Other Deployments'
  },
  groups: {
    name: 'group',
    nameId: 'groupId',
    Name: 'Group',
    names: 'groups',
    Names: 'Groups',
    NAMES: 'GROUPS',
    naming: 'group',
    Naming: 'Group',
    namings: 'groups',
    Namings: 'Groups'
  },
  keys: {
    name: 'key',
    nameId: 'keyId',
    Name: 'Key',
    names: 'keys',
    Names: 'Keys',
    NAMES: 'KEYS',
    naming: 'key',
    Naming: 'Key',
    namings: 'keys',
    Namings: 'Keys'
  },
  accounts: {
    name: 'account',
    nameId: 'accountId',
    Name: 'Account',
    names: 'accounts',
    Names: 'Accounts',
    NAMES: 'ACCOUNTS',
    naming: 'account',
    Naming: 'Account',
    namings: 'accounts',
    Namings: 'Accounts'
  },
  users: {
    name: 'user',
    nameId: 'userId',
    Name: 'User',
    names: 'users',
    Names: 'Users',
    NAMES: 'USERS',
    naming: 'user',
    Naming: 'User',
    namings: 'users',
    Namings: 'Users'
  },
  members: {
    name: 'member',
    nameId: 'memberId',
    Name: 'Member',
    names: 'members',
    Names: 'Members',
    NAMES: 'MEMBERS',
    naming: 'member',
    Naming: 'Member',
    namings: 'Members',
    Namings: 'Members'
  },
  reminders: {
    name: 'reminder',
    nameId: 'reminderId',
    Name: 'Reminder',
    names: 'reminders',
    Names: 'Reminders',
    NAMES: 'REMINDERS',
    naming: 'reminder',
    Naming: 'Reminder',
    namings: 'reminders',
    Namings: 'Reminders'
  },
  roles: {
    name: 'role',
    nameId: 'roleId',
    Name: 'Role',
    names: 'roles',
    Names: 'Roles',
    NAMES: 'ROLES',
    naming: 'role',
    Naming: 'Role',
    namings: 'roles',
    Namings: 'Roles'
  },
  costs: {
    name: 'cost',
    nameId: 'costId',
    Name: 'Cost',
    names: 'costs',
    Names: 'Costs',
    NAMES: 'COSTS',
    naming: 'cost',
    Naming: 'Cost',
    namings: 'costs',
    Namings: 'Costs'
  },
  domains: {
    name: 'domain',
    nameId: 'domainId',
    Name: 'Domain',
    names: 'domains',
    Names: 'Domains',
    NAMES: 'DOMAINS',
    naming: 'domain',
    Naming: 'Domain',
    namings: 'domains',
    Namings: 'Domains'
  },
  schedulers: {
    name: 'scheduler',
    nameId: 'schedulerId',
    Name: 'Scheduler',
    names: 'schedulers',
    Names: 'Schedulers',
    NAMES: 'SCHEDULERS',
    naming: 'scheduler',
    Naming: 'Scheduler',
    namings: 'schedulers',
    Namings: 'Schedulers'
  },
  services: {
    name: 'service',
    nameId: 'serviceId',
    Name: 'Service',
    names: 'services',
    Names: 'Services',
    NAMES: 'SERVICES',
    naming: 'service',
    Naming: 'Service',
    namings: 'services',
    Namings: 'Services'
  },
  permissions: {
    name: 'permission',
    nameId: 'permissionId',
    Name: 'Permission',
    names: 'permissions',
    Names: 'Permissions',
    NAMES: 'PERMISSIONS',
    naming: 'permission',
    Naming: 'Permission',
    namings: 'permissions',
    Namings: 'Permissions'
  },
  cloudAccountPermissions: {
    name: 'cloudAccountPermission',
    nameId: 'cloudAccountPermissionId',
    Name: 'CloudAccountPermission',
    names: 'cloudAccountPermissions',
    Names: 'CloudAccountPermissions',
    NAMES: 'CLOUD_ACCOUNT_PERMISSIONS',
    naming: 'cloud account permission',
    Naming: 'Cloud Account Permission',
    namings: 'cloud account permissions',
    Namings: 'Cloud Account Permissions'
  },
  cloudUserPermissions: {
    name: 'cloudUserPermission',
    nameId: 'cloudUserPermissionId',
    Name: 'CloudUserPermission',
    names: 'cloudUserPermissions',
    Names: 'CloudUserPermissions',
    NAMES: 'CLOUD_USER_PERMISSIONS',
    naming: 'cloud user permission',
    Naming: 'Cloud User Permission',
    namings: 'cloud user permissions',
    Namings: 'Cloud User Permissions'
  },
  deploymentPermissions: {
    name: 'deploymentPermission',
    nameId: 'deploymentPermissionId',
    Name: 'DeploymentPermission',
    names: 'deploymentPermissions',
    Names: 'DeploymentPermissions',
    NAMES: 'DEPLOYMENT_PERMISSIONS',
    naming: 'deployment permission',
    Naming: 'Deployment Permission',
    namings: 'deployment permissions',
    Namings: 'Deployment Permissions'
  },
  groupPermissions: {
    name: 'groupPermission',
    nameId: 'groupPermissionId',
    Name: 'GroupPermission',
    names: 'groupPermissions',
    Names: 'GroupPermissions',
    NAMES: 'GROUP_PERMISSIONS',
    naming: 'group permission',
    Naming: 'Group Permission',
    namings: 'group permissions',
    Namings: 'Group Permissions'
  },
  keyPermissions: {
    name: 'keyPermission',
    nameId: 'keyPermissionId',
    Name: 'KeyPermission',
    names: 'keyPermissions',
    Names: 'KeyPermissions',
    NAMES: 'KEY_PERMISSIONS',
    naming: 'key permission',
    Naming: 'Key Permission',
    namings: 'key permissions',
    Namings: 'Key Permissions'
  },
  repositoryPermissions: {
    name: 'repositoryPermission',
    nameId: 'repositoryPermissionId',
    Name: 'RepositoryPermission',
    names: 'repositoryPermissions',
    Names: 'RepositoryPermissions',
    NAMES: 'REPOSITORY_PERMISSIONS',
    naming: 'repository permission',
    Naming: 'Repository Permission',
    namings: 'repository permissions',
    Namings: 'Repository Permissions'
  }
}

export default w
